name: tests-payment

on:
  pull_request:
    paths:
      - "payment/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payment && npm install && npm run test:ci
